import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import matter from 'gray-matter';
import { atomicWrite } from './util/fs.mjs';

function extractSection(body, heading) {
  const match = body.match(new RegExp(`^## ${heading}\\s*\\n([\\s\\S]*?)(?=\\n## |\\s*$)`, 'm'));
  if (!match) return '';
  return match[1].trim();
}

function toDateString(val) {
  if (!val) return '';
  if (val instanceof Date) return val.toISOString().slice(0, 10);
  const s = String(val);
  if (s.length >= 10 && /^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
  return s;
}

export async function rebuildManifest(outputDir) {
  const entries = [];

  function walk(dir) {
    let items;
    try {
      items = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const item of items) {
      const fullPath = join(dir, item.name);
      if (item.isDirectory()) {
        walk(fullPath);
      } else if (item.name.endsWith('.md') && !item.name.startsWith('_')) {
        try {
          const content = readFileSync(fullPath, 'utf8');
          const { data, content: body } = matter(content);
          if (data.title && data.ref) {
            const dateStr = toDateString(data.date);
            entries.push({
              id: `RCA-${dateStr || 'unknown'}-${data.ref}`,
              title: data.title || '',
              date: dateStr,
              ref: data.ref || '',
              confidence: data.confidence || 'unknown',
              tags: data.tags || [],
              components: data.components || [],
              files: data.files || [],
              description: data.description || '',
              root_cause_snippet: extractSection(body, 'Root Cause').slice(0, 200),
              fix_snippet: extractSection(body, 'Fix').slice(0, 150),
              path: relative(outputDir, fullPath).replace(/\\/g, '/'),
            });
          }
        } catch {
          // skip unparseable files
        }
      }
    }
  }

  walk(outputDir);

  entries.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

  const headerLines = [
    '# Auto-generated by claude-rca. Do not edit manually.',
    `# Updated: ${new Date().toISOString()}`,
    `# Count: ${entries.length}`,
  ];

  const jsonLines = entries.map((e) => JSON.stringify(e));

  const output = [...headerLines, ...jsonLines].join('\n') + '\n';

  const manifestPath = join(outputDir, '_manifest.jsonl');
  await atomicWrite(manifestPath, output);
  return manifestPath;
}

/**
 * Load and parse the manifest file, returning an array of entry objects.
 * Returns [] if the manifest does not exist or cannot be read.
 * @param {string} outputDir
 * @returns {Array<Object>}
 */
export function loadManifest(outputDir) {
  const manifestPath = join(outputDir, '_manifest.jsonl');
  let raw;
  try {
    raw = readFileSync(manifestPath, 'utf8');
  } catch {
    return [];
  }
  const entries = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    try {
      entries.push(JSON.parse(trimmed));
    } catch {
      // skip malformed lines
    }
  }
  return entries;
}
