import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import matter from 'gray-matter';
import { atomicWrite } from './util/fs.mjs';

function toDateString(val) {
  if (!val) return '';
  if (val instanceof Date) return val.toISOString().slice(0, 10);
  const s = String(val);
  if (s.length >= 10 && /^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
  return s;
}

export async function rebuildManifest(outputDir) {
  const entries = [];

  function walk(dir) {
    let items;
    try {
      items = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const item of items) {
      const fullPath = join(dir, item.name);
      if (item.isDirectory()) {
        walk(fullPath);
      } else if (item.name.endsWith('.md') && !item.name.startsWith('_')) {
        try {
          const content = readFileSync(fullPath, 'utf8');
          const { data } = matter(content);
          if (data.title && data.ref) {
            const dateStr = toDateString(data.date);
            entries.push({
              id: `RCA-${dateStr || 'unknown'}-${data.ref}`,
              title: data.title || '',
              date: dateStr,
              ref: data.ref || '',
              confidence: data.confidence || 'unknown',
              tags: data.tags || [],
              components: data.components || [],
              files: data.files || [],
              description: data.description || '',
              path: relative(outputDir, fullPath).replace(/\\/g, '/'),
            });
          }
        } catch {
          // skip unparseable files
        }
      }
    }
  }

  walk(outputDir);

  entries.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

  const lines = [
    '# Auto-generated by claude-rca. Do not edit manually.',
    `# Updated: ${new Date().toISOString()}`,
    `# Count: ${entries.length}`,
    '',
  ];

  for (const e of entries) {
    lines.push(`- id: ${e.id}`);
    lines.push(`  title: "${e.title.replace(/"/g, '\\"')}"`);
    lines.push(`  date: ${e.date}`);
    lines.push(`  ref: ${e.ref}`);
    lines.push(`  confidence: ${e.confidence}`);
    lines.push(`  tags: [${e.tags.join(', ')}]`);
    if (e.components.length > 0) {
      lines.push(`  components: [${e.components.join(', ')}]`);
    }
    lines.push(`  files: [${e.files.join(', ')}]`);
    if (e.description) {
      lines.push(`  description: "${e.description.replace(/"/g, '\\"')}"`);
    }
    lines.push(`  path: ${e.path}`);
    lines.push('');
  }

  const manifestPath = join(outputDir, '_manifest.yaml');
  await atomicWrite(manifestPath, lines.join('\n'));
  return manifestPath;
}
