import { readdirSync, readFileSync } from 'node:fs';
import { join, relative, basename, resolve } from 'node:path';
import matter from 'gray-matter';
import { atomicWrite } from './util/fs.mjs';

function extractSection(body, heading) {
  const match = body.match(new RegExp(`^## ${heading}\\s*\\n([\\s\\S]*?)(?=\\n## |\\s*$)`, 'm'));
  if (!match) return '';
  return match[1].trim();
}

function toDateString(val) {
  if (!val) return '';
  if (val instanceof Date) return val.toISOString().slice(0, 10);
  const s = String(val);
  if (s.length >= 10 && /^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
  return s;
}

/**
 * Generate rca/llms.txt — a slim navigation index for AI tools.
 * Called automatically by rebuildManifest().
 * @param {string} outputDir
 * @param {Array<Object>} entries  - already-sorted manifest entries
 * @returns {Promise<string>}  - path to llms.txt
 */
export async function generateLlmsTxt(outputDir, entries) {
  const repoName = basename(outputDir === './rca' ? process.cwd() : resolve(outputDir, '..'));
  const recent = entries.slice(0, 20);

  // Build tag frequency map
  const tagCounts = {};
  for (const e of entries) {
    for (const t of e.tags || []) {
      tagCounts[t] = (tagCounts[t] || 0) + 1;
    }
  }
  const topTags = Object.entries(tagCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([tag, count]) => `  - ${tag} (${count} RCA${count === 1 ? '' : 's'})`);

  const lines = [
    `# RCA Corpus — ${repoName}`,
    '',
    `Root Cause Analysis documents generated by RCA-Ninja. Total: ${entries.length} RCA${entries.length === 1 ? '' : 's'}.`,
    '',
    '> For full search: `claude-rca search <query>` | Manifest: `rca/_manifest.jsonl`',
    '',
  ];

  if (recent.length > 0) {
    lines.push('## Recent RCAs (latest 20)', '');
    for (const e of recent) {
      const snippet =
        e.root_cause_snippet
          ? ` — ${e.root_cause_snippet.slice(0, 120).replace(/\n/g, ' ')}`
          : '';
      const tags =
        e.tags && e.tags.length > 0 ? ` [${e.tags.slice(0, 3).join(', ')}]` : '';
      lines.push(`- [${e.id}](${e.path}): ${e.title}${snippet}${tags}`);
    }
    lines.push('');
  }

  if (topTags.length > 0) {
    lines.push('## Top Tags', '');
    lines.push(...topTags);
    lines.push('');
  }

  lines.push('## Usage', '');
  lines.push('```bash');
  lines.push('claude-rca search "query"          # full-text search');
  lines.push('claude-rca search --tag <tag>       # filter by tag');
  lines.push('claude-rca search --files <path>    # find RCAs for a file');
  lines.push('claude-rca recent 5                 # 5 most recent');
  lines.push('claude-rca trends                   # corpus statistics');
  lines.push('```');

  const content = lines.join('\n') + '\n';
  const llmsTxtPath = join(outputDir, 'llms.txt');
  await atomicWrite(llmsTxtPath, content);
  return llmsTxtPath;
}

export async function rebuildManifest(outputDir) {
  const entries = [];

  function walk(dir) {
    let items;
    try {
      items = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const item of items) {
      const fullPath = join(dir, item.name);
      if (item.isDirectory()) {
        walk(fullPath);
      } else if (item.name.endsWith('.md') && !item.name.startsWith('_')) {
        try {
          const content = readFileSync(fullPath, 'utf8');
          const { data, content: body } = matter(content);
          if (data.title && data.ref) {
            const dateStr = toDateString(data.date);
            entries.push({
              id: `RCA-${dateStr || 'unknown'}-${data.ref}`,
              title: data.title || '',
              date: dateStr,
              ref: data.ref || '',
              confidence: data.confidence || 'unknown',
              tags: data.tags || [],
              components: data.components || [],
              files: data.files || [],
              description: data.description || '',
              root_cause_snippet: extractSection(body, 'Root Cause').slice(0, 200),
              fix_snippet: extractSection(body, 'Fix').slice(0, 150),
              path: relative(outputDir, fullPath).replace(/\\/g, '/'),
            });
          }
        } catch {
          // skip unparseable files
        }
      }
    }
  }

  walk(outputDir);

  entries.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

  const headerLines = [
    '# Auto-generated by claude-rca. Do not edit manually.',
    `# Updated: ${new Date().toISOString()}`,
    `# Count: ${entries.length}`,
  ];

  const jsonLines = entries.map((e) => JSON.stringify(e));

  const output = [...headerLines, ...jsonLines].join('\n') + '\n';

  const manifestPath = join(outputDir, '_manifest.jsonl');
  await atomicWrite(manifestPath, output);
  await generateLlmsTxt(outputDir, entries);
  return manifestPath;
}

/**
 * Load and parse the manifest file, returning an array of entry objects.
 * Returns [] if the manifest does not exist or cannot be read.
 * @param {string} outputDir
 * @returns {Array<Object>}
 */
export function loadManifest(outputDir) {
  const manifestPath = join(outputDir, '_manifest.jsonl');
  let raw;
  try {
    raw = readFileSync(manifestPath, 'utf8');
  } catch {
    return [];
  }
  const entries = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    try {
      entries.push(JSON.parse(trimmed));
    } catch {
      // skip malformed lines
    }
  }
  return entries;
}
